# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f15dd483edbea8a9c026864c16478c8973b9ded757a41fb15e39add857745f313887ae4f59f85f3ad371e26a920e5d3e7c1fa2dd04708a2ee45b8ef9cea44c

test:
  secret_key_base: 2d911df3c33fd653b356b7ab3ebc171833491decf8d6591225208b9a3695c26f93753cf5bfe2af520a70bc601ce1a2fea14bede44a0292f4d13063e1f4af8caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
